### ISSUE TITLE
Revisit DB field character limits

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#362]
The previous assumptions of max length required for package name, version failed 

See https://github.com/nexB/vulnerablecode/blob/4193543bc54a58e5cd750f0ed5c5fbabd056e380/vulnerabilities/data_source.py#L513

https://github.com/nexB/vulnerablecode/blob/4193543bc54a58e5cd750f0ed5c5fbabd056e380/vulnerabilities/data_source.py#L519

We need to set new max lengths for these fields in the models.py

**Comment by pombredanne** [comment]
@sbs2001 a good way may be to reuse the package url mixin that @tdruez crafted in https://github.com/package-url/packageurl-python/blob/291e11bea47f07616b94dc46eb489af4ba425658/src/packageurl/contrib/django/models.py#L115

Name and versions are 100 chars there and have been tested quite a bit in scancode.io AFAIK

**Comment by DennisClark** [comment]
2 questions: 
* has this issue been addressed already?  
* does the current emphasis on PURL identification make this issue non-essential?

**Comment by DennisClark** [comment]
A perusal of https://public.vulnerablecode.io/api/schema/ indicates that we still have length limits on package name and version (and other components of the PURL).  What remains to be determined is whether those limits are a serious problem.


```
    Package:
      type: object
      description: Lookup software package using Package URLs
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        purl:
          type: string
        type:
          type: string
          description: 'A short code to identify the type of this package. For example:
            gem for a Rubygem, docker for a container, pypi for a Python Wheel or
            Egg, maven for a Maven Jar, deb for a Debian package, etc.'
          maxLength: 16
        namespace:
          type: string
          description: Package name prefix, such as Maven groupid, Docker image owner,
            GitHub user or organization, etc.
          maxLength: 255
        name:
          type: string
          description: Name of the package.
          maxLength: 100
        version:
          type: string
          description: Version of the package.
          maxLength: 100
        qualifiers:
          type: string
          readOnly: true
        subpath:
          type: string
          description: Extra subpath within a package, relative to the package root.
          maxLength: 200
```
